### PR TITLE
Rat 1.4

### PR DESCRIPTION
**Pull request by haowang-bioinfo**
### Main improvements in this PR:
- Fixes ([PR 460](https://github.com/SysBioChalmers/Human-GEM/pull/460)):
  - fix: correct MAM03882 annotation, as reported in Mouse-GEM [#21](https://github.com/SysBioChalmers/Mouse-GEM/issues/21)
- Fixes ([PR 429](https://github.com/SysBioChalmers/Human-GEM/pull/429)):
  - feat: add Acod1(Irg1) gene and associated reaction, as discussed in Mouse-GEM [#20](https://github.com/SysBioChalmers/Mouse-GEM/issues/20)
- Features (commit f5f78450e7c6659bef5b9cd0dd48da35b82e7226):
  - feat: update ortholog pairs from Alliance of Genomes to ver `5.3.0`
- Style (commit cee1e295795e30064ed5c310748f566d6d89ffc2):
  - change human-rat ortholog file from `json` to `tsv`, as discussed in Mouse-GEM [#15](https://github.com/SysBioChalmers/Mouse-GEM/issues/15)

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
It would be great to note somewhere which version of Human-GEM this is based on, perhaps in the README.

**Comment by haowang-bioinfo** [comment]
> It would be great to note somewhere which version of Human-GEM this is based on, perhaps in the README.

I believe you've asked this question [before](https://github.com/SysBioChalmers/Mouse-GEM/pull/7), would be good fix this somehow

**Comment by mihai-sysbio** [comment]
> I believe you've asked this question [before](https://github.com/SysBioChalmers/Mouse-GEM/pull/7), would be good fix this somehow

Indeed I have - but I still can't find where the Human-GEM dependency is listed. I'm asking about this since I know there have been quite a few releases improving Human-GEM since the previous release of Rat-GEM.

**Comment by haowang-bioinfo** [comment]
> I still can't find where the Human-GEM dependency is listed

the quick answer is the dependency [file](https://github.com/SysBioChalmers/Mouse-GEM/blob/main/model/dependencies.txt) is in `main` branch only

**Comment by haowang-bioinfo** [comment]
probably we should replace this step with an automatic approach via a centralized [script](https://github.com/SysBioChalmers/Human-GEM/issues/421) in HumanGEM

**Review by mihai-sysbio — APPROVED** [review]

**Pull request merged**
